Repository shriya030/CS-Hut, pull requests merged in 2021-06, with the labels that each got.

#23 Added Preloader
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/HomePage/Banner.js
Labels: LGMSOC21, 🟨 Level2

#19 contact us page
  src/App.js
  src/Components/ContactUs.css
  src/Components/ContactUs.js
  src/HomePage/NavBar.js
Labels: LGMSOC21, 🟨 Level2

#25 added contributors in readme
  README.md
Labels: LGMSOC21, 🟩 Level1

#29 readme.md file
  README.md
Labels: LGMSOC21, 🟨 Level2

#26 changes in navbar
  src/HomePage/Aboutus.js
  src/HomePage/NavBar.css
  src/HomePage/NavBar.js
Labels: LGMSOC21, 🟩 Level1

#38 Database
  src/App.js
  src/Components/Tags.js
  src/Components/Tags/Databases.js
  src/Data/Databases.js
Labels: LGMSOC21, 🟧 Level3

#41 updated contributers section link which is not working --issue37
  README.md
Labels: LGMSOC21, 🟪 Level0

#58 update style of tags card
  package-lock.json
  src/Components/Tags.css
  src/Components/Tags.js
  src/Data/Databases.js
Labels: LGMSOC21, 🟨 Level2

#69 Update footer
  public/index.html
  src/Data/Languages.js
  src/HomePage/Footer.css
  src/HomePage/Footer.js
Labels: LGMSOC21, 🟨 Level2

#66 bug in language page
  src/Components/Learn.css
  src/Components/Tags/styles.css
  src/Data/Languages.js
Labels: LGMSOC21, 🟩 Level1

#75 Addition in database and framework
  src/Data/Databases.js
  src/Data/Frameworks.js
Labels: LGMSOC21, 🟧 Level3

#77 error page
  src/App.js
  src/Assets/notfound2.svg
  src/Components/ErrorPage.css
  src/Components/ErrorPage.js
Labels: LGMSOC21, 🟨 Level2

#76 changes in about section and update resources
  src/HomePage/Aboutus.css
  src/HomePage/Footer.css
  src/HomePage/Footer.js
  src/HomePage/NavBar.js
Labels: LGMSOC21, 🟩 Level1
